import express from 'express';
import path from 'path';
import crypto from 'crypto';
import pg from 'pg';
import { fileURLToPath } from 'url';
const {Pool}=pg;const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);
const app=express();
app.set('trust proxy',1);
app.use((req,res,next)=>{
  const proto=String(req.headers['x-forwarded-proto']||req.protocol||'').split(',')[0].trim().toLowerCase();
  if(proto&&proto!=='https')return res.redirect(301,`https://${req.get('host')}${req.originalUrl}`);
  res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');
  res.setHeader('Content-Security-Policy','upgrade-insecure-requests');
  res.setHeader('X-Content-Type-Options','nosniff');
  res.setHeader('X-Frame-Options','SAMEORIGIN');
  res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');
  next();
});
app.use(express.json({limit:'20mb'}));
app.use(express.static(path.join(__dirname,'public'),{index:false}));
const ADMIN_USER=process.env.ADMIN_USER||'admin',ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||crypto.randomBytes(12).toString('base64url');const sessions=new Map();
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?.includes('railway.internal')?false:{rejectUnauthorized:false}});
async function initDb(){await pool.query(`CREATE TABLE IF NOT EXISTS bookings(id UUID PRIMARY KEY,received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),booking_date TEXT,name TEXT NOT NULL,phone TEXT NOT NULL,car TEXT NOT NULL,year TEXT NOT NULL,vin TEXT NOT NULL,service TEXT NOT NULL,notes TEXT,language TEXT)`);console.log('ZEBAZ PostgreSQL database ready')}initDb().catch(e=>{console.error(e);process.exit(1)});
function cookie(req,n){const m=(req.headers.cookie||'').match(new RegExp('(?:^|; )'+n+'=([^;]*)'));return m?decodeURIComponent(m[1]):null}function auth(req,res,next){const t=cookie(req,'zebaz_admin');return t&&sessions.has(t)?next():res.status(401).json({ok:false,error:'Unauthorized'})}
app.post('/admin/login',(req,res)=>{const {username,password}=req.body||{};if(username!==ADMIN_USER||password!==ADMIN_PASSWORD)return res.status(401).json({ok:false,error:'Wrong username or password'});const t=crypto.randomBytes(32).toString('hex');sessions.set(t,Date.now());res.setHeader('Set-Cookie',`zebaz_admin=${t}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=86400`);res.json({ok:true})});
app.post('/admin/logout',auth,(req,res)=>{sessions.delete(cookie(req,'zebaz_admin'));res.setHeader('Set-Cookie','zebaz_admin=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/admin/api/bookings',auth,async(req,res)=>{try{const {rows}=await pool.query('SELECT id,received_at AS "receivedAt",booking_date AS date,name,phone,car,year,vin,service,notes,language FROM bookings ORDER BY received_at DESC');res.json({ok:true,bookings:rows,databaseReady:true})}catch(e){res.status(500).json({ok:false,error:'Database error'})}});
app.get('/admin/api/qr',auth,(req,res)=>res.json({ok:true,ready:true,database:true}));
app.get('/status',async(req,res)=>{try{await pool.query('SELECT 1');res.json({ready:true,database:true})}catch{res.status(503).json({ready:false,database:false})}});
function fromMessage(message=''){const get=k=>{const m=String(message).match(new RegExp('^'+k+':\\s*(.*)$','mi'));return m?m[1].trim():''};return{name:get('Name'),phone:get('Phone'),car:get('Car'),year:get('Year'),vin:get('VIN'),service:get('Service'),date:get('Date & Time'),notes:get('Notes')}}
app.post('/send-booking',async(req,res)=>{try{const parsed=fromMessage(req.body?.message),b=req.body?.booking||parsed;const r={id:crypto.randomUUID(),date:String(b.date||''),name:String(b.name||'').trim(),phone:String(b.phone||'').trim(),car:String(b.car||'').trim(),year:String(b.year||'').trim(),vin:String(b.vin||'').trim().toUpperCase(),service:String(b.service||'').trim(),notes:String(b.notes||'').trim(),language:String(b.language||'')};if(!r.name||!r.phone||!r.car||!r.year||r.vin.length!==17||!r.service)return res.status(400).json({ok:false,error:'Missing or invalid booking data'});await pool.query('INSERT INTO bookings(id,booking_date,name,phone,car,year,vin,service,notes,language) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[r.id,r.date,r.name,r.phone,r.car,r.year,r.vin,r.service,r.notes,r.language]);res.json({ok:true,saved:true,id:r.id})}catch(e){console.error('Booking save failed:',e.message);res.status(500).json({ok:false,error:'Could not save booking'})}});
const page=(file)=>(req,res)=>res.sendFile(path.join(__dirname,'public',file));
app.get('/',page('home.html'));
app.get(['/studio','/studio/'],page('studio.html'));
app.get(['/ppf','/ppf/'],page('index.html'));
app.get(['/fb-oil','/fb-oil/','/oil','/oil/'],page('fb-oil.html'));
app.get(['/carwash','/carwash/'],page('carwash.html'));
app.get(['/game-center','/game-center/','/game','/game/'],page('game-center.html'));
app.get(['/media','/media/'],page('media.html'));
app.get(['/ai','/ai/'],page('ai.html'));
app.get('/admin',page('admin.html'));
app.use((req,res)=>res.status(404).sendFile(path.join(__dirname,'public','home.html')));
const port=process.env.PORT||3000;app.listen(port,'0.0.0.0',()=>console.log(`ZEBAZ Group running on port ${port}`));